name: Deploy bot

on:
  push:
    branches: 
      - 'master'
  workflow_dispatch:
  
jobs: 
  build_bot:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract branch name
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr '/' '-')" >> $GITHUB_ENV
        id: extract_branch

      - name: Extract commit hash
        id: commit_hash
        run: |
          COMMIT_HASH=${GITHUB_SHA::7} # Get the first 7 characters of the commit hash
          echo "COMMIT_HASH=${COMMIT_HASH,,}" >> $GITHUB_ENV # Convert to lowercase
      
      - name: Login to GCR
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set version number
        run: |
          if [ -f "package.json" ]; then
            VERSION=v$(node -p "require('./package.json').version")-${{ steps.extract_branch.outputs.branch }}.${{ env.COMMIT_HASH }}
            echo "VERSION=${VERSION}" >> $GITHUB_ENV
            npm version "${VERSION}" --no-git-tag-version --allow-same-version
          else
            echo "package.json not found!"
            exit 1
          fi

      - name: Create env
        run: |
          echo "NODE_ENV=production" >> .env
          echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}" >> .env
          echo "VATUSA_API_KEY=${{ secrets.VATUSA_API_KEY }}" >> .env
          echo "SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}" >> .env
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          